### ISSUE TITLE
Failed to load the ionide-installer package

### ISSUE THREAD

**Issue by nosami** [ionide/ionide-installer#3]
[Enter steps to reproduce below:]

1. ...First time install
2. ...Open F# file in Atom

**Atom Version**: 1.0.15
**System**: Mac OS X 10.10.5
**Thrown From**: [ionide-installer](https://github.com/Ionide/ionide-installer) package, v1.1.0

### Stack Trace

Failed to load the ionide-installer package

```
At /Users/jason/.atom/packages/ionide-installer/lib/installer.js:2
    activate: => require("atom-package-deps").install("ionide-installer")
              ^^
Unexpected token =>

/Users/jason/.atom/packages/ionide-installer/lib/installer.js:2
    activate: => require("atom-package-deps").install("ionide-installer")
              ^^
SyntaxError: Unexpected token =>
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:411:25)
    at Object.defineProperty.value [as .js] (/Users/jason/Downloads/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Package.module.exports.Package.requireMainModule (/Users/jason/Downloads/Atom.app/Contents/Resources/app.asar/src/package.js:761:34)
    at /Users/jason/Downloads/Atom.app/Contents/Resources/app.asar/src/package.js:192:28
    at Package.module.exports.Package.measure (/Users/jason/Downloads/Atom.app/Contents/Resources/app.asar/src/package.js:169:15)
```

### Commands

```
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
atom-yeoman, v0.3.13
ionide-installer, v1.1.0
json-schema, v0.1.13
linter, v1.5.1
omnisharp-atom, v0.24.6

# Dev
No dev packages
```

**Comment by k2b6s9j** [comment]
My bad.

**Comment by Krzysztof-Cieslak** [comment]
Fixed in `1.1.2`

**Comment by nosami** [comment]
Thanks! I don't get the error any more - but it doesn't seem to be doing anything either. I get no syntax highlighting or anything like that. 

Does ionide-installer have any UI display to show you what it's doing?

**Comment by nosami** [comment]
I also noticed that omnisharp-atom kicked in for this fsharp solution. Will need to get omnisharp fixed to prevent that.

**Comment by Krzysztof-Cieslak** [comment]
Hmm... installing packages make take a while and after that it's advised to restart Atom. I might revert back some changes I've merged in last 15 minutes since I'm not sure if everything is working. 

And no, unfortunately there isn't any notification. I should add it

**Comment by nosami** [comment]
OK. No problem. Will try again later. I also created an OmniSharp ticket here https://github.com/OmniSharp/omnisharp-atom/issues/512

**Comment by Krzysztof-Cieslak** [comment]
OK, I've reverted to the version which is for sure working. So after updating installer to `1.1.3` everything should start installing.

As i said - it make take a while, so be patient. And restart Atom after everything (5 plugins + installer) showed up in settings view.

**Comment by nosami** [comment]
Ok, updated to 1.1.3. Will let you know how it goes.

**Comment by k2b6s9j** [comment]
The patch I am working on right now will allow it so that the user knows when things are done installing and will activate packages automatically.

**Comment by nosami** [comment]
looking good. 
<img width="525" alt="screen shot 2015-09-19 at 23 13 16" src="https://cloud.githubusercontent.com/assets/667194/9978403/13a58192-5f24-11e5-9925-00c3936a9ea2.png">

**Comment by nosami** [comment]
<img width="598" alt="screen shot 2015-09-19 at 23 16 57" src="https://cloud.githubusercontent.com/assets/667194/9978407/945c8222-5f24-11e5-8d16-bba3c6c68614.png">

Success! I have some reference errors, but I guess that is an fsautocomplete issue.

**Comment by Krzysztof-Cieslak** [comment]
@nosami Glad it's working, If you have any problems report them on `ionide-fsharp` repo (or other if problem with some specific package)

@k2b6s9j: It would be cool to have it :). But I will handle it tomorrow anyway, it's getting bit late here :)

**Comment by nosami** [comment]
Thanks :+1:
