### ISSUE TITLE
Failed to activate the ionide-installer package

### ISSUE THREAD

**Issue by lstrzepek** [ionide/ionide-installer#5]
[Enter steps to reproduce below:]

1. Install atom editor
2. Install Ionide-installer

**Atom Version**: 1.0.15
**System**: Microsoft Windows 10 Pro
**Thrown From**: [ionide-installer](https://github.com/Ionide/ionide-installer) package, v1.2.1

### Stack Trace

Failed to activate the ionide-installer package

```
At Cannot find module 'atom-package-deps'

Error: Cannot find module 'atom-package-deps'
  at Module._resolveFilename (module.js:334:15)
  at Function.Module._resolveFilename (C:\Users\Łukasz\AppData\Local\atom\app-1.0.15\resources\app.asar\src\module-cache.js:383:52)
  at Function.Module._load (module.js:284:25)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.activate (C:\Users\Łukasz\.atom\packages\ionide-installer\lib\installer.js:8:16)
  at Package.module.exports.Package.activateNow (C:\Users\Łukasz\AppData\Local\atom\app-1.0.15\resources\app.asar\src\package.js:245:19)
  at C:\Users\Łukasz\AppData\Local\atom\app-1.0.15\resources\app.asar\src\package.js:226:30
  at Package.module.exports.Package.measure (C:\Users\Łukasz\AppData\Local\atom\app-1.0.15\resources\app.asar\src\package.js:169:15)
  at Package.module.exports.Package.activate (C:\Users\Łukasz\AppData\Local\atom\app-1.0.15\resources\app.asar\src\package.js:218:14)
  at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\Łukasz\AppData\Local\atom\app-1.0.15\resources\app.asar\src\package-manager.js:486:21)
  at C:\Users\Łukasz\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\settings-view\lib\package-manager.js:371:29
  at exit (C:\Users\Łukasz\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\settings-view\lib\package-manager.js:60:16)
  at triggerExitCallback (C:\Users\Łukasz\AppData\Local\atom\app-1.0.15\resources\app.asar\src\buffered-process.js:213:47)
  at ChildProcess.<anonymous> (C:\Users\Łukasz\AppData\Local\atom\app-1.0.15\resources\app.asar\src\buffered-process.js:235:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:172:7)
  at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

```

### Commands

```
     -0:40.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:26.9.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:26.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
ionide-installer, v1.2.1

# Dev
No dev packages
```

**Comment by Krzysztof-Cieslak** [comment]
Using `cmd` or `PS` go to  `C:\Users\USERNAME\.atom\packages\ionide-installer`, run `apm install` from there, and try running Atom again.

**Comment by lstrzepek** [comment]
λ C:\Users\Łukasz\AppData\Local\atom\app-1.0.15\resources\app\apm\bin\apm.cmd install
Installing modules done

But still the same info after atom start

**Comment by Krzysztof-Cieslak** [comment]
Ok, that's interesting. Can You paste here content of `C:\Users\USERNAME\.atom\packages\ionide-installer\package.json` ?

**Comment by lstrzepek** [comment]
Sure:
===================
{
  "name": "ionide-installer",
  "main": "./lib/installer",
  "version": "1.2.1",
  "description": "Installer for Ionide project",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/Ionide/ionide-installer.git"
  },
  "license": "MIT",
  "engines": {
    "atom": ">=0.174.0 <2.0.0"
  },
  "dependencies": {
    "atom-package-deps": "^2.1.3"
  },
  "package-deps": [
    "atom-yeoman",
    "linter",
    "advanced-open-file",
    "ionide-fsharp",
    "ionide-paket",
    "ionide-fake",
    "ionide-fsi",
    "ionide-yeoman"
  ],
  "readme": "# Ionide-Installer\n\n## Contributing and copyright\n\nThe project is hosted on [GitHub](https://github.com/ionide/ionide-installer) where you can [report issues](https://github.com/ionide/ionide-installer/issues), fork\nthe project and submit pull requests.\n\nThe library is available under [MIT license](https://github.com/ionide/ionide-installer/blob/master/LICENSE.md), which allows modification and\nredistribution for both commercial and non-commercial purposes.\n\n## Code of Conduct\n\nThis project adheres to No Code of Conduct. We are all adults. We accept everyone's contributions. Nothing else matters.\n\nFor more information please visit the [No Code of Conduct](https://github.com/domgetter/NCoC) homepage.\n",
  "readmeFilename": "README.md",
  "bugs": {
    "url": "https://github.com/Ionide/ionide-installer/issues"
  },
  "homepage": "https://github.com/Ionide/ionide-installer#readme",
  "_id": "ionide-installer@1.2.1",
  "_shasum": "a3bc487584be4fefd10f45dd49e577207fb058b4",
  "_resolved": "file:..\\d-115822-26328-upnxow\\package.tgz",
  "_from": "..\\d-115822-26328-upnxow\\package.tgz",
  "_atomModuleCache": {
    "version": 1,
    "dependencies": [
      {
        "name": "atom-package-deps",
        "version": "2.1.3",
        "path": "node_modules\\atom-package-deps\\lib\\main.js"
      }
    ],
    "extensions": {
      ".js": [
        "lib\\installer.js",
        "node_modules\\atom-package-deps\\lib\\helper.js",
        "node_modules\\atom-package-deps\\lib\\main.js",
        "node_modules\\atom-package-deps\\lib\\view.js"
      ],
      ".json": [
        "node_modules\\atom-package-deps\\package.json",
        "package.json"
      ]
    },
    "folders": [
      {
        "paths": [
          "lib",
          ""
        ],
        "dependencies": {
          "atom-package-deps": "^2.1.3"
        }
      }
    ]
  }
}

**Comment by Krzysztof-Cieslak** [comment]
Does `C:\Users\USERNAME\.atom\packages\ionide-installer\node_modules\atom-package-deps\lib\main.js` exist?

**Comment by lstrzepek** [comment]
Yes, all three files with content:
    Directory: C:\Users\Łukasz\.atom\packages\ionide-installer\node_modules\atom-package-deps\lib


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----       22.09.2015     21:43           1100 helper.js
-a----       22.09.2015     21:43           1457 main.js
-a----       22.09.2015     21:43           1599 view.js

**Comment by Krzysztof-Cieslak** [comment]
That's exactly same as on my machine. Try to move whole `ionide-installer` folder to some different path (without Polish chars in path) and run `apm link` from it.

**Comment by lstrzepek** [comment]
Small progress after linking:

Installing ionide-installer dependencies
Installing atom-yeoman, linter, advanced-open-file, ionide-fsharp, ionide-paket, ionide-fake, ionide-fsi, ionide-yeoman

But nothing happen..

**Comment by Krzysztof-Cieslak** [comment]
Has it finished installation without any errors? If so, it should be good (unless Atom has really big problems with Polish chars in chat :( ). Try to open any F# file / project and start editing.

**Comment by lstrzepek** [comment]
It finnished with many errors on almost every package :( But hhlighting works on F# files :)

**Comment by Krzysztof-Cieslak** [comment]
Hmm... i don't really know what is problem. You can also try moving all `ionide-*` folders outside of path with Polish chars and run `apm install` and then `apm link` for each one

**Comment by steelbrain** [comment]
Well, let's try an old school fix for this

Step 1: Close atom
Step 2: Do
```
mv ~/.atom ~/.atom-backup
apm install ionide-installer
```
Step 3: Run atom

Et Voila! Problem solved :tada:
