### ISSUE TITLE
Installation failure on MacOS 10.11

### ISSUE THREAD

**Issue by thefiddler** [ionide/ionide-installer#6]
It appears that the installer is looking for Mono in /usr/bin/mono.

"'/usr/bin/mono' could not be spawned. Is it installed and on your path? If so please open an issue on the package spawning the process."

Due to the System Integrity Protection (SIP) feature, it is not possible to install or link Mono in this location. On my system, Mono is installed in /usr/local/bin/mono and is on my path.

**Comment by Krzysztof-Cieslak** [comment]
Please set path to your mono installation (usr/local/bin) in both `ionide-fsharp` and `ionide-paket` plugin settings.

**Comment by dezmoleski** [comment]
So, since this caused errors during installation, are there any necessary steps to take after setting the path to /usr/local/bin in those two packages? Re-run post-installation scripts? Or should everything be OK after just setting the path for those two plugins?

**Comment by Krzysztof-Cieslak** [comment]
Everything should be OK after setting path.
