### ISSUE TITLE
ionide is looking for mono in wrong place

### ISSUE THREAD

**Issue by reidarsollid** [ionide/ionide-installer#7]
Hi,

I am using or am trying to use IonIDE for OS X El Capitan. Mono is installed on /usr/local/bin/mono and IonIDE is looking for in /usr/bin/mono, can I change the search path?

**Comment by Krzysztof-Cieslak** [comment]
Please set path to your mono installation (usr/local/bin) in both ionide-fsharp and ionide-paket plugin settings.
