### ISSUE TITLE
can't install on atom

### ISSUE THREAD

**Issue by vilinski** [ionide/ionide-installer#9]
can't install iodide-installer on mac anymore. Have worked all the time before. After installation also tried to set the path to mono to /usr/local/bin instead of /usr/bin, because of el capitan. What can I try otherwise?

> index.js:52 Window load time: 1502ms
> /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:982 /deep/ combinator is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.
> /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:982 ::shadow pseudo-element is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.
> events.js:141 Uncaught Error: spawn /usr/bin/mono ENOENT
> /Users/me/.atom/packages/ionide-paket/lib/paket.js:1038 ReferenceError: path is not defined(…)
> PaketService__spawnSilent$	@	/Users/me/.atom/packages/ionide-paket/lib/paket.js:1038
> PaketService__UpdatePaketSilent$	@	/Users/me/.atom/packages/ionide-paket/lib/paket.js:786
> Paket__activate$	@	/Users/me/.atom/packages/ionide-paket/lib/paket.js:1067
> (anonymous function)	@	/Users/me/.atom/packages/ionide-paket/lib/paket.js:1472
> module.exports.AtomFSharpPaket.activate	@	/Users/me/.atom/packages/ionide-paket/lib/paket.js:1483
> module.exports.Package.activateNow	@	/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:181
> (anonymous function)	@	/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:155
> module.exports.Package.measure	@	/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92
> (anonymous function)	@	/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:148
> module.exports.Package.activate	@	/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:145
> module.exports.PackageManager.activatePackage	@	/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:526
> (anonymous function)	@	main.js:36
> stdout	@	helper.js:20,
> (anonymous function)	@	/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:85
> emitOne	@	events.js:77
> emit	@	events.js:169
> readableAddChunk	@	_stream_readable.js:146
> Readable.push	@	_stream_readable.js:110
> onread	@	net.js:523

**Comment by davidpodhola** [comment]
Experienced the same. 
![mono-ionide-spawn-problem](https://cloud.githubusercontent.com/assets/436605/13717300/e9d4eb46-e7e0-11e5-9eec-e11a21d10299.PNG)

Needed both linking `mono ` to `/usr/bin/mono` with 

`sudo ln -s /usr/local/bin/mono /usr/bin/mono`

and later few more settings in Atom see screenshots below. Now it is working.

![mono-ionide-spawn-problem-fixed1](https://cloud.githubusercontent.com/assets/436605/13717309/f2d85b60-e7e0-11e5-8c6e-66610fe28af2.PNG)

![mono-ionide-spawn-problem-fixed](https://cloud.githubusercontent.com/assets/436605/13717318/0278df68-e7e1-11e5-9e36-0035150691b5.PNG)
![atom-ionide-mac-settings](https://cloud.githubusercontent.com/assets/436605/13717320/04ee0b10-e7e1-11e5-95bf-9cca0c9d41e7.PNG)

**Comment by vilinski** [comment]
* My config.cson differs from your only on "ionide-paket" MonoPath is identical to one in "ionide-fsharp".
* I have no /usr/bin/mono, only /usr/local/bin/mono
* Uninstalled Xamarin 6 Beta and entire mono stuff. Installed stable Xamarin.
* Now ionide works. No clue what exactly is changed.

**Comment by darakimaia** [comment]
Hi, 
I'm experiencing the same - mono is installed on `/usr/local/bin` (installed through Xamarin Studio ages ago). Package is trying to run it from `/usr/bin`.

**Comment by vilinski** [comment]
you must not symlink mono executable, workaround:
- set the path to it in both packages ionide-fsharp and ionide-paket.

Another problem is `fsharpi`. It is just a shell script, which has $MONO variable, which points to the wrong location.
- locate the fsharpi - `which fsharpi` - usually it is in /usr/local/bin/fsharpi
- replace $MONO variable with its full path - last line.
